#!/usr/bin/env ruby

require 'cri'
require 'rabbitmq-spec'

root_cmd = Cri::Command.define do
  name        'rabbitmq-spec'
  usage       'rabbitmq-spec command [options]'

  flag   :h,  :help, 'show help for rabbitmq-spec' do |_value, cmd|
    puts cmd.help
    exit 0
  end

  run do |_opts, _args, cmd|
    puts cmd.help
    exit 0
  end
end

cmd_setup = Cri::Command.define do
  name        'setup'
  usage       'rabbitmq-spec setup [options]'
  summary     'Configure RabbitMQ usging the passed specifications files'

  required :u, :"broker-url", 'AMPQ Broker Url', argument: :required

  run do |opts, args, _cmd|
    if args.count.zero?
      puts 'Please pass a folder or a file name.'
      exit 0
    elsif opts[:'broker-url'].nil?
      puts 'Please provide the broker url.'
      exit 0
    else
      paths = args.map do |folder_path|
        File.expand_path(folder_path.to_s)
      end
      RabbitMQSpec::Setup.run(files_paths: paths, url: opts)
      puts 'Setup Finished'
    end
    exit 0
  end
end

root_cmd.add_command(cmd_setup)

root_cmd.run(ARGV)
